### ISSUE TITLE
Keyword arguments, when were they first used?

### ISSUE THREAD

**Issue by olleolleolle** [httprb/form_data#16]
Hello,

I'm wondering about Ruby keyword arguments in `form_data`. Keyword arguments are a Ruby 2.0 feature. (Ruby 2.1 gave us "required keyword arguments". [Source](https://robots.thoughtbot.com/ruby-2-keyword-arguments))

Which version introduced their usage?

I'm wondering because I am trying [to make reel build on JRuby 1.7.x](https://github.com/celluloid/reel/pull/243)

**Comment by ixti** [comment]
Sorry about that. Will fix asap. The idea is following:

1. release `1.0.3` with kwargs being replaced with optional opts hash and add min required ruby version to gemspec as `1.9`
2. v2+ will have kwargs and min ruby requirement `2.1`

Will that work for you?

**Comment by olleolleolle** [comment]
Super nice with a plan! 

This will work perfectly.

**Comment by olleolleolle** [comment]
...and now it builds! Thanks!
