### ISSUE TITLE
Custom encoding method

### ISSUE THREAD

**Issue by FabienChaynes** [httprb/form_data#22]
Hi,

I encountered an incompatibility issue in the [Twitter gem](https://github.com/sferik/twitter) between `http-form_data` and [simple_oauth](https://github.com/laserlemon/simple_oauth). More explanation are given in [this issue](https://github.com/sferik/twitter/issues/677#issuecomment-360976258).

Basically [here (http-form_data)](https://github.com/httprb/form_data/blob/e938a40c0a8acc3f19792b085b77ddafc649581e/lib/http/form_data/urlencoded.rb#L16) and [there (simple_oauth)](https://github.com/laserlemon/simple_oauth/blob/4a375da4e213667e356e98a9e2bc3c3b8b969d67/lib/simple_oauth/header.rb#L32) the encoding is not done the same way.
`http-form_data` uses [URI.encode_www_form](https://apidock.com/ruby/URI/encode_www_form/class) which uses [URI.encode_www_form_component](https://apidock.com/ruby/URI/encode_www_form_component/class) which doesn't convert `*`, while `simple_oauth` encodes `*`. The twitter API requires `*` to be encoded as explained [in this post](https://twittercommunity.com/t/using-in-search-query-not-allowed/10519#post_4).

I understand that it's not a bug in `http-form_data` per se, but would you be OK to merge a PR allowing users of the gem to override the method encoding data in [HTTP::FormData::Urlencoded#initialize](https://github.com/httprb/form_data/blob/e938a40c0a8acc3f19792b085b77ddafc649581e/lib/http/form_data/urlencoded.rb#L16) and provide their own? By default it'd obviously still be `::URI.encode_www_form` so it'd be a transparent change.
If it sounds somewhat acceptable to you, I'd be glad to work on something and to submit a PR.

Thanks :slightly_smiling_face:

**Comment by ixti** [comment]
I'm OK with this. Please open a PR so we can start a discussion on API changes :D

**Comment by FabienChaynes** [comment]
Neat!
Will do :+1:

**Comment by clarkbab** [comment]
Hi @ixti, any chance of patching the version with this addition?

**Comment by ixti** [comment]
@clarkbab Sure. Will do shortly

**Comment by ixti** [comment]
Released as v2.1.1
